name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger deploy script
        run: |
          curl -X POST \
          -H "Authorization: Token ${{ secrets.PA_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"command":"bash /home/rafalzacher1/smartify/deploy.sh"}' \
          https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/